FROM node:16-alpine

WORKDIR /app

COPY ["package.json","yarn.lock","tsconfig.json","tsconfig.build.json","./"]

RUN yarn install 

COPY ["./src","./src"]

ENV PORT=5000

EXPOSE 5000

EXPOSE 9229

CMD ["yarn","run","start:dev"]